### ISSUE TITLE
BART Installation Problem

### ISSUE THREAD

**Issue by liuwenman** [jbisbee1/BARP#3]
Hi James,

I have a problem with installing the BARP package<see below for more details>.  It seems the source codes need to be updated? Could you help me out, please?

Many thanks!

Wenman
---------------------

I got error messages if I install from github: 

ERROR: lazy loading failed for package ‘BARP’ 
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BARP’ 
Error: Failed to install 'BARP' from GitHub: (converted from warning) installation of package ‘/var/folders/n8/2zpwtww10sn5q5r2dszhg6g40000gn/T//RtmpgF1TH5/file2625b2a175/BARP_0.0.1.0001.tar.gz’ had non-zero exit status 

if I go to the link above, download the package installation document and install from local, I got another set of error messages: 

ERROR: lazy loading failed for package ‘BARP’ 
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BARP’ Warning in install.packages : installation of package ‘/Users/wenmanliu/Downloads/BARP_0.0.1.0001.tar.gz’ had non-zero exit status

**Comment by jbisbee1** [comment]
Can you try adding `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)` to your script before calling `install_github('jbisbee1/BARP')`?

**Comment by liuwenman** [comment]
Still having error messages:

The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JVM could not be found
Error: package ‘rJava’ could not be loaded
In addition: Warning messages:
1: In system("/usr/libexec/java_home", intern = TRUE) :
  running command '/usr/libexec/java_home' had status 1
2: In fun(libname, pkgname) :
  Cannot find JVM library 'NA/lib/server/libjvm.dylib'
Install Java and/or check JAVA_HOME (if in doubt, do NOT set it, it will be
detected)
Execution halted
ERROR: lazy loading failed for package ‘BARP’
* removing
‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BARP’
Warning message:
In i.p(...) :
  installation of package
‘/var/folders/n8/2zpwtww10sn5q5r2dszhg6g40000gn/T//RtmpjyFOj4/file3c9e711f0679/BARP_0.0.1.0001.tar.gz’
had non-zero exit status

**Comment by jbisbee1** [comment]
The challenges associated with installing java -- particularly on a Windows machine -- are a separate issue from the BARP package. (The [vignette](https://github.com/jbisbee1/BARP/blob/master/vignettes/BARP.pdf) warns users about this challenge. A quick Google search should help, although [this method](https://www.r-statistics.com/2012/08/how-to-load-the-rjava-package-after-the-error-java_home-cannot-be-determined-from-the-registry/) linked in the vignette three years ago is increasingly out-of-date.) The [documentation](https://github.com/kapelner/bartMachine) for the `bartMachine` package on which BARP depends might also be of use.

**Comment by liuwenman** [comment]
Thank you. I will go through the links. I'm using a Mac not a windows
though.
