### ISSUE TITLE
Issue with Y Specification

### ISSUE THREAD

**Issue by spurioushound** [jbisbee1/BARP#4]
I was working with the code provided in the vignette and got the error attached (using R 4.2.1)

I specified "supp_marriage" as a separate object Y and the code ran through correctly.

<img width="1008" alt="Screenshot 2022-12-16 at 2 23 46 PM" src="https://user-images.githubusercontent.com/24193466/208173495-13c32812-7c8b-4d21-9b07-9efd377ab806.png">

**Comment by jbisbee1** [comment]
Thanks for the heads up. I'll take a look and get back to you, although it will probably be a minute given the end of semester crunch.

**Comment by jbisbee1** [comment]
I think I fixed it, although please let me know if the issue persists. It seems that bartMachine wasn't recognizing variables passed within the environment (although other algorithms didn't have the same problem).
