### ISSUE TITLE
Issues Installing Vignette and Running It

### ISSUE THREAD

**Issue by apetrihos** [jbisbee1/BARP#5]
Hello,

I tried to install the package with Vignettes, and I continuously got this error message.

 Quitting from lines 122-123 [VigFig2-barpploteval] (BARP.Rmd)
   Error: processing vignette 'BARP.Rmd' failed with diagnostics:
   This bartMachine object was loaded from an R image but was not serialized.
     Please build bartMachine using the option "serialize = TRUE" next time.
   
   --- failed re-building ‘BARP.Rmd’

Also, whenever I try to run the following code from the vignette my R-Session crashes.

Any ideas to either of these problems?

options(java.parameters = "-Xmx8g")
library(BARP)
library(grid)
library(bartMachine)
library(gridExtra)
load('~/Downloads/barp_vignette_6_2019.RData')

data("gaymar")
census06 <- census06 %>% merge(svy %>% 
                                 dplyr::select(state,stateid) %>% 
                                 distinct())

factors <- c("region","gXr","state")

census06[factors] <- lapply(census06[factors],factor)

svy[c(factors)] <- lapply(svy[c(factors)],factor)

barp.obj <- barp(y = "supp_gaymar",
                 x = c("age","educ","gXr",
                       "pvote","religcon",
                       "state","region"),
                 dat = svy,census = census06,
                 geo.unit = "state",
                 proportion = "n",
                 seed = 1021,
                 serialize = TRUE)

**Comment by apetrihos** [comment]
It seems that the barp function will crash my session when running this command from the barp.SL function (Line 315)

do.call("cbind", lapply(seq(k), FUN = .predFun, 
    lib = library$library, dataY = Y, dataX = X, newX = newX, 
    whichScreen = whichScreen, family = family, id = id, 
    obsWeights = obsWeights, verbose = verbose, control = control, 
    libraryNames = libraryNames))

**Comment by apetrihos** [comment]
Installing the Java SDK instead of the regular Java fixed this for me

**Comment by jbisbee1** [comment]
Sorry for the tardy reply (been moving apartments). Can you tell me your OS / compute environment?
